### ISSUE TITLE
Nothing about PATCH

### ISSUE THREAD

**Issue by doctordesh** [bfontaine/httpdoc#1]
First issue! Woo!

Maybe this is more of a discussion thing, but there is nothing about the PATCH method. 

```
→ httpdoc patch
ERROR: Unknown resource
```

Here's a link to a RFC about the PATCH HTTP method. http://tools.ietf.org/html/rfc5789

Is it maybe so that PATCH is not part of the standard HTTP definition?

**Comment by bfontaine** [comment]
Thank, fixed!
